theme = "my_nord"

[editor]
true-color = true
auto-format = false
auto-completion = false
completion-replace = true
scrolloff = 5
bufferline = "multiple"
color-modes = true
# line-number = "relative"
# indent-guides = { render = true }

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.soft-wrap]
enable = true
# max-wrap = 40
# max-indent-retain = 0

[editor.statusline]
# left = ["mode", "spinner", "file-name", "separator", "version-control", "separator"]
# center = ["version-control"]

[keys.normal]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "goto_line_start"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after", "goto_line_start"]
"A-S-up" = ["extend_to_line_bounds", "yank", "paste_before", "goto_line_start"]
"A-S-down" = ["extend_to_line_bounds", "yank", "move_line_down", "paste_before", "move_line_up", "goto_line_start", "move_line_down"]
C-r = ":sh make && ./VoidEngine"

[keys.insert]
"A-up" = ["extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before", "goto_line_start"]
"A-down" = ["extend_to_line_bounds", "delete_selection", "paste_after", "goto_line_start"]
"A-S-up" = ["extend_to_line_bounds", "yank", "paste_before", "goto_line_start", "move_line_up"]
"A-S-down" = ["extend_to_line_bounds", "yank", "move_line_down", "paste_before", "move_line_up", "goto_line_start"]
