[[language]]
name = "python"
scope = "source.python"
injection-regex = "python"
file-types = ["py", "pyi"]
shebangs = ["python"]
auto-format = false
roots = ["venv/"]
comment-token = "#"
language-server = { command = "pyright-langserver", args = ["--stdio"] }
# language-server = { command = "jedi-language-server" }
config = """
{
  "python": {
    "analysis": {
      "autoSearchPaths": true,
      "diagnosticMode": "workspace"
    }
  }
}
"""
# TODO: pyls needs utf-8 offsets
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "c"
scope = "source.c"
injection-regex = "c"
file-types = ["c", "h"] # TODO: ["h"]
roots = []
comment-token = "//"
language-server = { command = "clangd" }
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "bash"
scope = "source.bash"
injection-regex = "(shell|bash|zsh|sh)"
file-types = ["sh", "bash", "zsh", ".bash_login", ".bash_logout", ".bash_profile", ".bashrc", ".profile", ".zshenv", ".zlogin", ".zlogout", ".zprofile", ".zshrc", "APKBUILD", "PKGBUILD", "eclass", "ebuild", "bazelrc", "Makefile"]
shebangs = ["sh", "bash", "dash"]
roots = []
comment-token = "#"
language-server = { command = "bash-language-server", args = ["start"] }
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "json"
scope = "source.json"
injection-regex = "json"
file-types = ["json", "gltf"]
roots = []
language-server = { command = "vscode-json-language-server", args = ["--stdio"] }
auto-format = true
config = { "provideFormatter" = true }
indent = { tab-width = 2, unit = "  " }

